package com.friends.velocity;

/** Generated by the build (velocity/src/main/templates): {@code @Plugin(version)} needs a compile-time constant. */
final class BuildConstants {
    static final String VERSION = "${version}";

    private BuildConstants() {}
}
